export const mockUserList = [
    {
        "_id": "5ca86ccd83051410fada71fd",
        "index": 0,
        "guid": "94b37c9b-4172-4133-88f0-eb9a84c6bffd",
        "isActive": false,
        "picture": "https://randomuser.me/api/portraits/men/0.jpg",
        "firstName": "Jones",
        "lastName": "Lindsey",
        "email": "joneslindsey@nimon.com",
        "phone": "+1 (865) 548-2695",
        "address": "  Tyhee, Missouri",
        "about": "Mollit ad do cupidatat esse adipisicing duis duis. Anim irure fugiat elit incididunt quis pariatur. Nulla eiusmod consequat sint dolor ut pariatur excepteur occaecat et dolore est fugiat. Cillum elit elit deserunt aliquip dolore consectetur quis ullamco ullamco non. Magna sint laboris adipisicing velit ea excepteur voluptate deserunt mollit incididunt cupidatat. Dolor ex laborum minim nostrud minim laborum ipsum et. Aliquip id nisi ex cillum nostrud nisi do ea laborum Lorem Lorem sint nulla ea.\r\n",
        "registered": "2014-12-04T12:00:01 -01:00",
        "role": "admin",
        "tags": [
            "Lorem",
            "fugiat",
            "laboris",
            "veniam",
            "pariatur",
            "eu",
            "in"
        ]
    },
    {
        "_id": "5ca86ccd9319287f9ab16a7e",
        "index": 1,
        "guid": "0cc592af-6a73-4028-8147-53259305b003",
        "isActive": true,
        "picture": "https://randomuser.me/api/portraits/men/1.jpg",
        "firstName": "Johns",
        "lastName": "Richardson",
        "email": "johnsrichardson@nimon.com",
        "phone": "+1 (811) 405-3642",
        "address": "  Drytown, South Carolina",
        "about": "Ex officia anim ad et nostrud veniam ea pariatur fugiat nostrud amet ipsum. Aliquip commodo occaecat fugiat cupidatat et anim consectetur ex sit aute excepteur. Aliquip eu incididunt laboris nisi pariatur. Consequat nisi sint ea magna laboris anim cupidatat excepteur anim ad nulla. Anim anim ipsum aliqua officia culpa voluptate Lorem. Mollit ut consectetur consequat veniam sunt irure culpa magna anim sint. Anim voluptate aute eiusmod non excepteur eiusmod est fugiat nulla dolore sit cupidatat eu.\r\n",
        "registered": "2018-02-12T02:28:39 -01:00",
        "role": "employee",
        "tags": [
            "ea",
            "sit",
            "incididunt",
            "esse",
            "ut",
            "consectetur",
            "nulla"
        ]
    },
    {
        "_id": "5ca86ccda40852994800f313",
        "index": 2,
        "guid": "9643d5fd-3b3c-4351-bf62-5de8c585fc3b",
        "isActive": false,
        "picture": "https://randomuser.me/api/portraits/men/2.jpg",
        "firstName": "Priscilla",
        "lastName": "Horn",
        "email": "priscillahorn@nimon.com",
        "phone": "+1 (931) 454-3804",
        "address": "  Shelby, Maine",
        "about": "Exercitation dolore velit deserunt ea eu quis aute aliqua consectetur dolor aute qui ex. Laborum magna aute esse officia tempor aliquip eu labore est adipisicing duis excepteur. Laboris excepteur cupidatat officia tempor. Consectetur nulla ut id anim eiusmod. Eu dolore eu ea sunt velit ullamco sunt ex. Amet mollit aliquip in voluptate qui exercitation aute eu elit elit est.\r\n",
        "registered": "2016-08-07T01:33:31 -02:00",
        "role": "employee",
        "tags": [
            "magna",
            "mollit",
            "qui",
            "sunt",
            "laboris",
            "ex",
            "duis"
        ]
    },
    {
        "_id": "5ca86ccd990f8bb91642eaa8",
        "index": 3,
        "guid": "8a4905ad-8252-4b81-8eba-eb3579229190",
        "isActive": false,
        "picture": "https://randomuser.me/api/portraits/men/3.jpg",
        "firstName": "Hobbs",
        "lastName": "Underwood",
        "email": "hobbsunderwood@nimon.com",
        "phone": "+1 (963) 470-3328",
        "address": "  Wilsonia, Virginia",
        "about": "In occaecat nisi proident incididunt nisi consequat dolor id amet ullamco deserunt cupidatat. Non consectetur do deserunt amet irure mollit. Occaecat enim cupidatat consequat Lorem nostrud qui sunt cillum irure commodo. Ea velit et id eiusmod. Elit exercitation incididunt id non. Laborum adipisicing magna sint sint anim ut eu sint do ullamco cillum.\r\n",
        "registered": "2014-01-10T10:42:22 -01:00",
        "role": "employee",
        "tags": [
            "officia",
            "amet",
            "minim",
            "in",
            "culpa",
            "voluptate",
            "excepteur"
        ]
    },
    {
        "_id": "5ca86ccd282290153f008090",
        "index": 4,
        "guid": "73c9f50c-5a10-4659-8bd8-302d12bcda9c",
        "isActive": true,
        "picture": "https://randomuser.me/api/portraits/men/4.jpg",
        "firstName": "Marcia",
        "lastName": "Alvarado",
        "email": "marciaalvarado@nimon.com",
        "phone": "+1 (984) 503-3414",
        "address": "  Grandview, California",
        "about": "Adipisicing ad exercitation dolor aliquip aliqua eu reprehenderit enim incididunt commodo. In deserunt Lorem esse elit ullamco Lorem ipsum quis eu eu magna id. Incididunt nisi culpa nostrud fugiat commodo. Laborum in nostrud est adipisicing enim eu Lorem aliqua ipsum proident pariatur velit. Quis laboris id ut enim enim in sint ea. Aliqua dolore non pariatur deserunt consequat veniam eiusmod tempor dolor et dolor fugiat id quis.\r\n",
        "registered": "2015-01-14T02:46:49 -01:00",
        "role": "employee",
        "tags": [
            "ad",
            "laboris",
            "dolore",
            "sit",
            "laboris",
            "ad",
            "enim"
        ]
    },
    {
        "_id": "5ca86ccda43032f2389d071a",
        "index": 5,
        "guid": "6643728b-9f9e-416b-9ee9-41c2c02a15bc",
        "isActive": true,
        "picture": "https://randomuser.me/api/portraits/men/5.jpg",
        "firstName": "Nadia",
        "lastName": "Terry",
        "email": "nadiaterry@nimon.com",
        "phone": "+1 (845) 595-2399",
        "address": "  Munjor, Pennsylvania",
        "about": "Ad reprehenderit ullamco elit aliqua eu enim. Ut ipsum reprehenderit adipisicing mollit qui veniam. Enim pariatur amet esse reprehenderit. Veniam excepteur proident eu veniam minim laborum dolore excepteur magna ad dolore commodo nulla. Excepteur commodo fugiat excepteur labore ipsum laboris nostrud.\r\n",
        "registered": "2015-04-02T03:11:28 -02:00",
        "role": "ceo",
        "tags": [
            "magna",
            "fugiat",
            "aliquip",
            "cupidatat",
            "est",
            "id",
            "pariatur"
        ]
    },
    {
        "_id": "5ca86ccdea920e4ddcf173a3",
        "index": 6,
        "guid": "61423706-49f9-4c81-9a6f-f4df1892bb64",
        "isActive": false,
        "picture": "https://randomuser.me/api/portraits/men/6.jpg",
        "firstName": "Randall",
        "lastName": "Brown",
        "email": "randallbrown@nimon.com",
        "phone": "+1 (848) 520-2672",
        "address": "  Epworth, New Jersey",
        "about": "Tempor nisi quis laborum esse laboris duis ad occaecat amet laboris Lorem nulla culpa. Amet qui cillum qui deserunt sit ex fugiat aute magna. Id nostrud culpa pariatur exercitation qui deserunt Lorem mollit excepteur culpa proident dolore ex. Irure excepteur ea fugiat eu deserunt cillum nisi ex ex non est ipsum nulla nostrud. Tempor in magna dolore nostrud magna id Lorem consectetur culpa quis ad.\r\n",
        "registered": "2016-05-12T06:24:34 -02:00",
        "role": "manager",
        "tags": [
            "laboris",
            "non",
            "labore",
            "culpa",
            "quis",
            "nulla",
            "excepteur"
        ]
    }
];